project:
  type: website
  render:
    - terminal_help.qmd
  post-render: touch _site/.nojekyll

website:
  title: "Folio Landing"
  navbar:
    background: primary
    left:
      - href: README.md
        text: Home
      - terminal_help.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


##
# project:
#   title: "Folio"
#   output-dir: temp




