project:
  type: website
  render: 
    - notebooks/terminal_help.qmd
    - "!test/"

website:
  title: "Folio Landing"
  navbar:
    background: primary
    left:
      - href: notebooks/terminal_help.qmd
        text: Home
      - notebooks/terminal_help.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


##
# project:
#   title: "Folio"
#   output-dir: temp




