project:
  type: website
  output-dir: docs
  render: 
    - notebooks/terminal_help.qmd
    - "!test/"

website:
  title: "Folio Landing"
  site-url: "https://amsandler.github.io/folio/"
  navbar:
    background: primary
    left:
      - href: notebooks/terminal_help.qmd
        text: Home
      - notebooks/terminal_help.qmd

format:
  html:
    theme: cosmo
    toc: true


##
# project:
#   title: "Folio"
#   output-dir: temp




